name: update-scoop-manifest

on:
  release:
    types: [published]

jobs:
  update-scoop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scoop-bucket
        uses: actions/checkout@v4
        with:
          repository: montekkundan/scoop-bucket
          token: ${{ secrets.GITHUB_TOKEN }}
          path: scoop-bucket

      - name: Update yo.json manifest
        run: |
          VERSION=${{ github.event.release.tag_name }}
          cd scoop-bucket
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" yo.json
          sed -i "s|\"url\": \"https://github.com/.*/yo-.*-x86_64-pc-windows-msvc.zip\"|\"url\": \"https://github.com/lershi-devlabs/yo/releases/download/$VERSION/yo-$VERSION-x86_64-pc-windows-msvc.zip\"|" yo.json
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add yo.json
          git commit -m "Update yo to $VERSION"
          git push 